import pluginNest from 'eslint-plugin-nestjs';

export default [
  {
    plugins: { nestjs: pluginNest },
    ...pluginNest.configs.recommended,
    rules: {
      'nestjs/use-validation-pipe': 'error',
      'nestjs/use-class-validator': 'error',
      'nestjs/no-lifecycle-method-param-type': 'error',
      'nestjs/no-misused-promises': 'error',
      'nestjs/no-misused-scopes': 'error',
      'nestjs/no-exported-injectable': 'warn',
      'nestjs/no-metatype': 'warn',
      'nestjs/use-injectable': 'error',
      'nestjs/use-method-decorator': 'warn',
      'nestjs/use-guards': 'warn',
      'nestjs/use-interceptors': 'warn',
      'nestjs/use-pipes': 'warn',
      'nestjs/use-filters': 'warn',
      'nestjs/use-exception-filter': 'warn',
      'nestjs/use-module': 'warn',
      'nestjs/no-extraneous-dependencies': 'warn',
      'nestjs/no-invalid-decorator': 'error',
      'nestjs/no-missing-decorator': 'error',
      'nestjs/no-async-method-without-await': 'warn',
      'nestjs/no-async-callback': 'warn',
      'nestjs/no-invalid-parameter-decorator': 'error',
      'nestjs/no-injectable-on-constructor': 'error',
      'nestjs/use-provider-inject': 'warn',
      'nestjs/no-unused-dependency': 'warn',
      'nestjs/no-misused-dependency-injection': 'warn',
    },
  },
];
